### ISSUE TITLE
ph_with_vg causes error in pptx

### ISSUE THREAD

**Issue by rlusch** [davidgohel/rvg#14]
When trying to create a powerpoint using ph_with_vg, the powerpoint is created, but has massive error when opening.
![image](https://user-images.githubusercontent.com/12199400/31684188-922abb7e-b344-11e7-9f72-d30e2c510547.png)
![image](https://user-images.githubusercontent.com/12199400/31684252-b121a768-b344-11e7-81aa-ab903e13c860.png)

Here is some code I was able to put together to recreate my problem.
```
require(ggplot2)
require(officer)
require(rvg)
require(magrittr)
require(forecast)

gg <- autoplot(ts(1:24, start = c(2016, 1), f = 12))

my_pres <- read_pptx() %>% 
  add_slide(layout = "Title and Content", master = "Office Theme") %>%
  ph_with_text(type = "title", str = "A title") %>%
  ph_with_vg(code = plot(1:24), type = "body")  %>%
  #ph_with_vg(code = print(gg), type = "body") %>%
  #ph_with_text(type = "body", str = "And content") %>%
  print(target = "test_no_template.pptx")
```

The lines that have been noted out were used to make sure that I could still add text into that portion of the powerpoint, which I could, and that the issue was also happening with ggplot, which it is.

This occurred on a Windows 7 installation, using R version 3.4.2 (32-bit), officer version 0.1.8, Rcpp 0.12.13, and rvg version 0.1.4.

Please let me know if there is anything I can do to help resolve the issue.

**Comment by davidgohel** [comment]
Maybe a constraint on rvg version I should write...

Could you try with:

1. rvg 1.6 from CRAN

If still not working with:

2. rvg and officer from Github

**Comment by rlusch** [comment]
I thought I had an updated version of rvg, I updated to 1.6 and it worked as expected.  By the way, you got to this issue VERY fast!  Thank you!

**Comment by davidgohel** [comment]
:) 

yes, too fast, I have lot of documents to scan right now and I think I am unconsciously trying to avoid these scans...
