### ISSUE TITLE
Install issue with Mac OS (High Sierra)

### ISSUE THREAD

**Issue by md0u80c9** [davidgohel/rvg#15]
Hi David,

I'm having difficulty installing the package on Mac OS. The last lines of the install look like this:

installing to /Library/Frameworks/R.framework/Versions/3.4/Resources/library/rvg/libs
** R
** inst
** tests
** preparing package for lazy loading
Error in dyn.load(file, DLLpath = DLLpath, ...) : 
  unable to load shared object '/Library/Frameworks/R.framework/Versions/3.4/Resources/library/gdtools/libs/gdtools.so':
  dlopen(/Library/Frameworks/R.framework/Versions/3.4/Resources/library/gdtools/libs/gdtools.so, 6): Library not loaded: /opt/X11/lib/libcairo.2.dylib
  Referenced from: /Library/Frameworks/R.framework/Versions/3.4/Resources/library/gdtools/libs/gdtools.so
  Reason: image not found
ERROR: lazy loading failed for package ‘rvg’
* removing ‘/Library/Frameworks/R.framework/Versions/3.4/Resources/library/rvg’
Installation failed: Command failed (1)
Warning message:
In strptime(x, fmt, tz = "GMT") : unknown timezone 'default/Europe/London'
> 

gdtools appears to be installed.

This is the output from the command line to check Cairo is installed OK:

Drews-laptop:~ andrewhill$ brew info cairo
cairo: stable 1.14.10 (bottled), HEAD
Vector graphics library with cross-device output support
https://cairographics.org/
/usr/local/Cellar/cairo/1.14.10 (118 files, 5.8MB) *
  Poured from bottle on 2017-10-31 at 22:04:30
From: https://github.com/Homebrew/homebrew-core/blob/master/Formula/cairo.rb
==> Dependencies
Build: pkg-config ✔
Required: freetype ✔, fontconfig ✔, libpng ✔, pixman ✔, glib ✔
==> Requirements
Optional: x11 ✘
==> Options
--with-x11
	Build with x11 support
--HEAD
	Install HEAD version
Drews-laptop:~ andrewhill$ 

I suspect this problem, is something to do with changes to library paths under Mac OS (there were a lot of changes to library paths with El Capitan IIRC, so they don't behave in an entirely UNIX-like way).

Any thoughts welcome!

**Comment by md0u80c9** [comment]
Assuming my presumption is correct that this is a library paths issue, I suspect this document will be helpful:

https://developer.apple.com/library/content/documentation/DeveloperTools/Conceptual/DynamicLibraries/100-Articles/UsingDynamicLibraries.html

**Comment by hrbrmstr** [comment]
I've been running 10.13 since the first beta and use rvg and have not had
this issue.

**Comment by davidgohel** [comment]
I don't have that issue neither.

This is about `gdtools`, not about `rvg`. Can you run the following (all R sessions should be closed):

```
brew update
brew upgrade
brew reinsall cairo
```

Then from a new R session:

```
install.packages("gdtools", type = "source", repos = "https://cran.rstudio.com")
```

You should then be able to install `rvg`.

**Comment by md0u80c9** [comment]
This looks to have fixed things! Thankyou very much!

**Comment by markhwhiteii** [comment]
@davidgohel this helped me not get errors when I `library(rvg)` on my local Macbook. However, I'm thinking about using this in a Shiny app that I deploy via Docker container that runs Debian. Will I need to install cairo in the Dockerfile in that container, or is this an issue localized to macOS?
