### ISSUE TITLE
Suggestion: take ggplot2 object as alternative to code in ph_with_rv

### ISSUE THREAD

**Issue by md0u80c9** [davidgohel/rvg#16]
Hi,

Just a very quick suggestion. I wonder whether as an alternative for the ‘code’ parameter it would be possible to accept ggplot2 objects (or other plot objects).

The main benefit for this is that instead of having to draw the chart inline, you can render the plots in separate functions and then pass them to the PowerPoint renderer.

**Comment by moodymudskipper** [comment]
I came to say the same thing.

Meawhile it's possibe to use `code=plot(my_plot)`, instead of `code = my_plot` but making the function recognise the input as a `ggplot` object would shorten the code and prevent some future head scratches from users.

**Comment by md0u80c9** [comment]
Yes that is exactly what I do in my code, but it makes it more readable and idiot-proofed if the function checks the object type and performs the plot if needed.

**Comment by davidgohel** [comment]
OK.

argument `ggobj` has been added.
