### ISSUE TITLE
Installation problem

### ISSUE THREAD

**Issue by Nicolabo** [davidgohel/rvg#2]
Hi,
I really want to see `ggiraph` package in action. Thus I installed `gdtools` and then I tried to install `rvg` but I get this error: What does it mean?

`> devtools::install_github('davidgohel/rvg')`
Downloading GitHub repo davidgohel/rvg@master
Installing rvg
Skipping 1 packages not available: gdtools
...
`  --library='/Library/Frameworks/R.framework/Versions/3.2/Resources/library' --install-tests `

`* installing *source* package ‘rvg’ ...`
`** libs`
clang++ -I/Library/Frameworks/R.framework/Resources/include -DNDEBUG  -I/usr/local/include -I/usr/local/include/freetype2 -I/opt/X11/include -I"/Library/Frameworks/R.framework/Versions/3.2/Resources/library/Rcpp/include" -I"/Library/Frameworks/R.framework/Versions/3.2/Resources/library/gdtools/include"   -fPIC  -Wall -mtune=core2 -g -O2  -c common.cpp -o common.o
clang++ -I/Library/Frameworks/R.framework/Resources/include -DNDEBUG  -I/usr/local/include -I/usr/local/include/freetype2 -I/opt/X11/include -I"/Library/Frameworks/R.framework/Versions/3.2/Resources/library/Rcpp/include" -I"/Library/Frameworks/R.framework/Versions/3.2/Resources/library/gdtools/include"   -fPIC  -Wall -mtune=core2 -g -O2  -c rvg.cpp -o rvg.o
clang++ -I/Library/Frameworks/R.framework/Resources/include -DNDEBUG  -I/usr/local/include -I/usr/local/include/freetype2 -I/opt/X11/include -I"/Library/Frameworks/R.framework/Versions/3.2/Resources/library/Rcpp/include" -I"/Library/Frameworks/R.framework/Versions/3.2/Resources/library/gdtools/include"   -fPIC  -Wall -mtune=core2 -g -O2  -c str_width.cpp -o str_width.o
`str_width.cpp:8:37: error: no member named 'str_extents' in namespace 'gdtools'`
`  Rcpp::NumericVector xx = gdtools::str_extents(str, fontname, fontsize, bold, italic );`
`                           ~~~~~~~~~^`
`str_width.cpp:12:37: error: no member named 'str_extents' in namespace 'gdtools'`
`  Rcpp::NumericVector xx = gdtools::str_extents(str, fontname, fontsize, bold, italic );`
`                           ~~~~~~~~~^`
`str_width.cpp:16:37: error: no member named 'str_metrics' in namespace 'gdtools'`
`  Rcpp::NumericVector xx = gdtools::str_metrics(str, fontname, fontsize, bold, italic );`
`                           ~~~~~~~~~^`
`3 errors generated.`
`make: *** [str_width.o] Error 1`
`ERROR: compilation failed for package ‘rag’`
`* removing ‘/Library/Frameworks/R.framework/Versions/3.2/Resources/library/rvg’`
`ERROR: Command failed (1)`

Thanks!

**Comment by davidgohel** [comment]
Hi,

This will need a little bit of work. For now, it's *broken* but things should be OK in 2/3 weeks.

**Comment by Nicolabo** [comment]
Thanks for your quick response, I am looking forward to see the effect!

**Comment by davidgohel** [comment]
Sorry for the delay.

`rvg` is on cran now. 

David

**Comment by Nicolabo** [comment]
Oo thanks!
