### ISSUE TITLE
ph_with_vg and geom_sf

### ISSUE THREAD

**Issue by ckluss** [davidgohel/rvg#21]
thx for your great package! Is it possible to use `ph_with_vg` with `geom_sf` too?
http://ggplot2.tidyverse.org/reference/ggsf.html

In the following example I get a slide with background but no map

```
library(tidyverse)
library(sf)
library(officer)
library(rvg)

nc <- sf::st_read(system.file("shape/nc.shp", package = "sf"), quiet = TRUE)
g1 <- nc %>% ggplot() + geom_sf(aes(fill = AREA))

g1

doc <- read_pptx() %>%
  add_slide(layout = "Title and Content", master = "Office Theme") %>%
  ph_with_vg(code = print(g1), type = "body") %>%
  print(target = "my_plot.pptx") 
```

Thank you very much
Christof

**Comment by davidgohel** [comment]
Hi,

That's because I forgot to implement `path`... Thanks for reporting this issue.

I will push a fix probably this week

**Comment by ckluss** [comment]
cool, thank you very much!

**Comment by davidgohel** [comment]
Hi, sorry for the delay

The actual github version should fix this issue.
