### ISSUE TITLE
R specific or extendable to other languages

### ISSUE THREAD

**Issue by Florian-Roessler** [davidgohel/rvg#22]
Hi,

I think this is a great package and I was wondering how tight it is associated with R/ggplot specific graphic instructions? Unfortunately my main language is Python (don't hit me 😋) so from what I can understand is that ggplot instructions are send to the c code which returns the office open xml code which in turn officer can then use to produce a slide containing that graphic. Is the C code limited to ggplot instructions or could it also deal with matplotlib (or for that matter other libraries) instructions easily?

If there is no way to easily make them work together I guess this is a quick issue to close.

Cheers,
Florian

**Comment by davidgohel** [comment]
Hi,

Interesting, I never thought about it.

> main language is Python (don't hit me 😋)

Deal! :) I wish I knew python better than I do! 

It's not only ggplot instructions. It works with all R graphics managed by the R graphical system (base plot, grid, lattice and ggplot2). 

It does not work with graphical htmlwidgets as they are producing graphics via javascript.

> [graphical instructions] are send to the c code which returns the office open xml code which in turn officer can then use to produce a slide containing that graphic

exactly

> could it also deal with matplotlib (or for that matter other libraries) instructions easily?

I don't know, only if there is a way to redirect them via the R graphic system... I don't think package `reticulate` is dealing with python graphical system and and have no other idea. 

The only solution I see now (or I am aware of) would be to create a `savefig` new output option... And I don't really understand what it implies in term of work.

**Comment by Florian-Roessler** [comment]
Hi,

thanks for the reply. I guess either writing a version of rvg to do the same for python instructions would be the long term goal. Short term piping the instructions into R graphical system (with all the issues that this might lead to) is probably the fastest option. I will have a look into things.
