### ISSUE TITLE
Text boxes moved around after export with body_add_vg

### ISSUE THREAD

**Issue by tomwenseleers** [davidgohel/rvg#30]
Just received this request about an issue of text boxes being slightly moved around after using my export::graph2doc function, which relies on rvg::body_add_vg :
[export::graph2office moves axis labels around](https://stackoverflow.com/questions/58591852/exportgraph2office-moves-axis-labels-around?noredirect=1#comment103524938_58591852)

I notice that the function body_add_vg will be deprecated though, and mentions
"The function is maintained but using it should be avoided: Word text boxes, the elements used to put text in a graphic, are adding extra space on top and bottom of the shape. As there is no clear rule available to handle that, it makes impossible to compute what should be the exact position of a text. This can affect the whole rendering of the graphic. The function should then be considered as a failed experience. An alternative is to use EMF format, this will not allow editing the graphic but the display is made as vector graphic."
What is the recommended way to go ahead then, and bring my package in line with the latest developments in rvg & officer, and still allow export to Word documents? Also what could be the cause of the shifted text boxes? Can Word text boxes not be exported to have zero margins on either side?

**Comment by davidgohel** [comment]
Dear Tom

Yes, you should not use `body_add_vg` for the reasons mentioned in the doc. 

> [...] and still allow export to Word documents

You can still export to Word document but you can not use rvg for Word format (not with an editable graph)

> Also what could be the cause of the shifted text boxes?

https://github.com/davidgohel/rvg/blob/master/R/dml_docx.R#L30

> Can Word text boxes not be exported to have zero margins on either side?

I don't know. sorry.

**Comment by tomwenseleers** [comment]
Thanks for letting me know... Noticed the same problem actually occurred if I export to Powerpoint using the rvg function ph_with_vg_at. Is that to be expected? I notice that it in the docs it now recommends to use the function ph_with.dml instead. Would that resolve the issue you reckon? Just asking so I know how I can keep my package up to date with the changes you are planning in rvg... cheers, Tom

**Comment by tomwenseleers** [comment]
Thanks for that! Will update my code to use ph_with then, that should be no problem... If I look at the Powerpoint output file above I notice similar problems though, with the text boxes not being quite correctly placed - e.g. the X axis labels touch the X axis ticks, which onscreen there is a slight space in between, and the Y axis labels are also placed a little bit too high. Also, the line widths of the axis tick marks in the exported powerpoint is different (1.07 pt) than the line width of the plot bounding box (1.49 pt), whereas in the original ggplot2 onscreen they are the same width. Any idea if these things could be fixed?

**Comment by tomwenseleers** [comment]
Hi David,
No I was just using your own code that you posted in your own answer here above and compared the PPT that you posted (which was the same as what I got on my machine)  with what I got on my screen. I also didn't have that font mentioned on SO on my machine, but one can use any font on your system and one still gets the same problem as far as I can see... I'll post this as a new issue then no probs and also post my sessionInfo().

**Comment by tomwenseleers** [comment]
OK put reproducible example at https://github.com/davidgohel/rvg/issues/31
