### ISSUE TITLE
Trouble exporting a xyplot from the lattice package

### ISSUE THREAD

**Issue by Cortex85** [davidgohel/rvg#32]
Hi,
after updating to Version 0.2.2 I can't create a PPTX from a xyplot in Lattice anymore (which worked before with "ph_with_vg"). Is there any option to export the plot to Powerpoint?

Example: 
library(lattice)
library(officer)
library(rvg)
library(dplyr)

states <- data.frame(state.x77,
                     state.name = dimnames(state.x77)[[1]],
                     state.region = state.region)
Example <- dml(code = 
                xyplot(Murder ~ Population | state.region, data = states,
                groups = state.name,
                panel = function(x, y, subscripts, groups) {
                ltext(x = x, y = y, labels = groups[subscripts], cex=1, fontfamily = "HersheySans")
                })
              )

my_pres <-
  read_pptx(path = "C:/Users/webera/Documents/template_r_v002_16_9.pptx") %>% 
  add_slide(layout="pptxrGrafik1", master = "Larissa") %>% 
  ph_with(Example, location = ph_location_fullsize())

I get the error message Fehler in doc_parse_raw(x, encoding = encoding, base_url = base_url, as_html = as_html,  :   StartTag: invalid element name [68]

Here is my session info:
R version 3.6.1 (2019-07-05)
Platform: x86_64-w64-mingw32/x64 (64-bit)
Running under: Windows 7 x64 (build 7601) Service Pack 1

Matrix products: default

Random number generation:
 RNG:     Mersenne-Twister 
 Normal:  Inversion 
 Sample:  Rounding 
 
locale:
[1] LC_COLLATE=German_Germany.1252  LC_CTYPE=German_Germany.1252    LC_MONETARY=German_Germany.1252
[4] LC_NUMERIC=C                    LC_TIME=German_Germany.1252    

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base     

other attached packages:
[1] gdtools_0.2.1   dplyr_0.8.3     rvg_0.2.2       officer_0.3.6   lattice_0.20-38

loaded via a namespace (and not attached):
 [1] Rcpp_1.0.3        assertthat_0.2.1  crayon_1.3.4      digest_0.6.23     grid_3.6.1       
 [6] R6_2.4.1          magrittr_1.5      pillar_1.4.2      zip_2.0.4         rlang_0.4.2      
[11] uuid_0.1-2        rstudioapi_0.10   xml2_1.2.2        tools_3.6.1       glue_1.3.1       
[16] purrr_0.3.3       compiler_3.6.1    pkgconfig_2.0.3   systemfonts_0.1.1 base64enc_0.1-3  
[21] htmltools_0.4.0   tidyselect_0.2.5  tibble_2.1.3

**Comment by davidgohel** [comment]
You can read the example here: https://davidgohel.github.io/rvg/#rvg-package

it shows how it works (you didn't use `dml`)

**Comment by Cortex85** [comment]
Thank you, I'm afraid I still did not get it, I think I used the dml (code=...) - command like in the example!?

**Comment by davidgohel** [comment]
lattice objects have to be printed (as ggplot objects) to produce a plot. 

```
library(lattice)
library(officer)
library(rvg)
library(dplyr)

states <- data.frame(state.x77,
  state.name = dimnames(state.x77)[[1]],
  state.region = state.region
)
Example <- dml(
  code =
    print(xyplot(Murder ~ Population | state.region,
      data = states,
      groups = state.name,
      panel = function(x, y, subscripts, groups) {
        ltext(x = x, y = y, labels = groups[subscripts], cex = 1, fontfamily = "HersheySans")
      }
    ))
)

my_pres <-
  read_pptx() %>%
  add_slide() %>%
  ph_with(Example, location = ph_location_fullsize()) %>%
  print(target = "test.pptx")
```

**Comment by Cortex85** [comment]
All right, thank you very much for your quick response!

**Comment by davidgohel** [comment]
you're welcome. I found the result difficult to edit, is it usual?

**Comment by Cortex85** [comment]
Oh, you are right, I took the example from the Lattice package help file. In general there are no problems editing the graph I usually create with this package.

**Comment by davidgohel** [comment]
ok, thanks for the feedback.
