### ISSUE TITLE
Error in UseMethod("ph_with", value)

### ISSUE THREAD

**Issue by GithubRplots** [davidgohel/rvg#34]
Hi, 
I am trying to export a ggsurvplot plot to .pptx using rvg. I accomplished this roughly a year ago but using the newest rvg Version, I keep getting the following error: 

> Error in UseMethod("ph_with", value) : 
  no applicable method for 'ph_with' applied to an object of class "c('ggsurvplot', 'ggsurv', 'list')"

Please find the reproducible example and session Infos below. 
`# Reproducible example ----------------------------------# 
library(officer)
library(rvg)
library(survival)
library(ggplot2)
library(survminer)

# survival plot
fit<- survfit(Surv(time, status) ~ sex, data = lung)
plot_ggsurv<-ggsurvplot(fit, data = lung)

# initiate export
fileout <- tempfile(fileext = ".pptx")
doc_1 <- read_pptx()
sz <- slide_size(doc_1)

doc_1 <- add_slide(doc_1)
doc_1 <- ph_with(x = doc_1, value = plot_ggsurv,
                   location = ph_location_type(type = "body"),
                   bg = "transparent" )
doc_1 <- ph_with(x = doc_1, value = "graphic title",
                   location = ph_location_type(type="title") )
`
using rvg 0.2.4 and R version 3.6.3 (2020-02-29) 
Is there a new function that can handle ggsurvplots?

Thanks in advance!

**Comment by davidgohel** [comment]
You need to use `dml` function. See first example here: https://davidgohel.github.io/rvg/ and here https://davidgohel.github.io/rvg/reference/dml.html for more details

````
# Reproducible example ----------------------------------#
library(officer)
library(rvg)
library(survival)
library(ggplot2)
library(survminer)

fit<- survfit(Surv(time, status) ~ sex, data = lung)
plot_ggsurv<-ggsurvplot(fit, data = lung)

fileout <- tempfile(fileext = ".pptx")
doc_1 <- read_pptx()
sz <- slide_size(doc_1)

doc_1 <- add_slide(doc_1)
doc_1 <- ph_with(x = doc_1, value = dml(code = print(plot_ggsurv, newpage = FALSE)),
                 location = ph_location_type(type = "body"),
                 bg = "transparent" )
doc_1 <- ph_with(x = doc_1, value = "graphic title",
                 location = ph_location_type(type="title") )
print(doc_1, target = "test.pptx")
````

**Comment by GithubRplots** [comment]
Hi David, thanks for yr reply. Tired running the example above using dml function using the first example you mentioned in yr post. Getting the following error message now: 

> Error in read_xml.raw(charToRaw(enc2utf8(x)), "UTF-8", ..., as_html = as_html,  : 
  StartTag: invalid element name [68]

Please see the amended code below, how can I best improve this? 

`library(officer)
library(rvg)
library(survival)
library(ggplot2)
library(survminer)`

`fit<- survfit(Surv(time, status) ~ sex, data = lung)
plot_ggsurv<-ggsurvplot(fit, data = lung)


anyplot = dml(code = plot_ggsurv, bg = "wheat")

doc <- read_pptx()
doc <- add_slide(doc, "Title and Content", "Office Theme")
doc <- ph_with(doc, anyplot, location = ph_location_fullsize())
fileout <- tempfile(fileext = ".pptx")
print(doc, target = fileout)`

(Using rvg 0.2.4 and R version 3.6.3 (2020-02-29))

**Comment by davidgohel** [comment]
You can copy the code I wrote, see `dml` arguments - you need also to read documentation, the one of `dml` and the one of `print. ggsurvplot`.

`dml(code = print(plot_ggsurv, newpage = FALSE))`
