### ISSUE TITLE
Name drawing objects for `ggplot2` charts created using `rvg::dml`

### ISSUE THREAD

**Issue by daviddiviny** [davidgohel/rvg#43]
This is a nice to have but it would be great if there was a way to name/label the objects created for editable vector graphics. 
As far as I can tell, the numbering of points in a `geom_point` scatter chart seems to follow the underlying data. 

![image](https://user-images.githubusercontent.com/6833387/140456003-950c3ace-66f7-470d-b735-5b4fbe50a1be.png)

**Comment by daviddiviny** [comment]
No worries @davidgohel ,thanks for your response. 
Is it possible for `officer` or `rvg` to rename them? I don't really know much about how the functions work (other than by interacting with the OOXML).

**Comment by davidgohel** [comment]
In very short, ggplot instructions are transmitted to R graphic system that only know it has to draw points, lines, etc. But it has no idea where that instruction come from, and we can't associate other parameters to the call. 

No really, don't waste time on that point, I already did. You would spend a huge amount of time for little gain (although I don't really know what is your *business case*)
