### ISSUE TITLE
Issues with rvg and ggplot2

### ISSUE THREAD

**Issue by itsdalmo** [davidgohel/rvg#5]
#### Issues

1. rvg creates a white panel background for ggplot2 objects (there is a rectangle inside the plots with a solid white fill), even though `theme(panel.background = element_blank())` is specified for the plot. This did not use to be an issue before the latest release on CRAN. **You have to look at the examples to see this issue**. 

2. Peculiar output in `ggplot2` when using `geom_bar` (possible other geoms as well) with manually specified limits on y-axis (possibly x-axis also). See pictures below, where PNG is the correct output.

![skjermbilde2](https://cloud.githubusercontent.com/assets/6603877/13432311/49b64a30-dfcd-11e5-88ee-9c37979147d9.PNG)
![skjermbilde](https://cloud.githubusercontent.com/assets/6603877/13432318/51b068ba-dfcd-11e5-8e41-171f4b84539d.PNG)

#### Example output
[ReporteRs - blank_canvas.pptx](https://github.com/davidgohel/rvg/files/153038/ReporteRs.-.blank_canvas.pptx)
[RVG - blank_canvas.pptx](https://github.com/davidgohel/rvg/files/153039/RVG.-.blank_canvas.pptx)
[ReporteRs - ylimited_regular barchart.pptx](https://github.com/davidgohel/rvg/files/153040/ReporteRs.-.ylimited_regular.barchart.pptx)
[RVG - ylimited_regular barchart.pptx](https://github.com/davidgohel/rvg/files/153042/RVG.-.ylimited_regular.barchart.pptx)
[ReporteRs - ylimited_stacked barchart.pptx](https://github.com/davidgohel/rvg/files/153044/ReporteRs.-.ylimited_stacked.barchart.pptx)
[RVG - ylimited_stacked barchart.pptx](https://github.com/davidgohel/rvg/files/153046/RVG.-.ylimited_stacked.barchart.pptx)

#### Example code

```r
library(ggplot2)

plot_to_pptx <- function(plt, title) {
  doc <- ReporteRs::pptx()
  fname <- paste0(sub("\\s", "_", tolower(title)), ".pptx")

  # ReporteRs (vector)
  doc <- ReporteRs::addSlide(doc, slide.layout = "Title and Content")
  doc <- ReporteRs::addTitle(doc, title)
  doc <- ReporteRs::addPlot(doc, fun = print, x = plt, vector.graphic = TRUE)
  
  # ReporteRs (png)
  doc <- ReporteRs::addSlide(doc, slide.layout = "Title and Content")
  doc <- ReporteRs::addTitle(doc, title)
  doc <- ReporteRs::addPlot(doc, fun = print, x = plt, vector.graphic = FALSE)
  
  # Save 
  ReporteRs::writeDoc(doc, file = paste0("ReporteRs - ", fname))
  
  # rvg
  rvg::write_pptx(paste0("RVG - ", fname), print(plt))
  invisible()
}

# 1 - Blank canvas not working
plt <- ggplot(data = mtcars, aes(x = hp, y = mpg))
plt <- plt + geom_point() + theme_bw() + theme(panel.background = element_blank(), plot.background = element_blank())
plot_to_pptx(plt = plt, title = "Blank Canvas")

# 2 - stacked barchart
library(dplyr)
df <- mtcars %>%
  mutate(cyl = factor(paste(cyl, "cyl"), levels = paste(c(4, 6, 8), "cyl"))) %>%
  mutate(am = factor(ifelse(am == 0L, "No", "Yes"))) %>%
  group_by(am, cyl) %>%
  summarise(mpg = mean(mpg))
  
plt <- ggplot(data = df, aes(x = cyl, y = mpg, group = am, fill = am)) + geom_bar(stat = "identity") 
plot_to_pptx(plt = plt, title = "Stacked barchart")

# With ylimit
plt <- plt + scale_y_continuous(limits=c(10L, 50L), oob = scales::rescale_none) 
plot_to_pptx(plt = plt, title = "Ylimited stacked barchart")

# 3 - Regular barchart
plt <- ggplot(data = df, aes(x = cyl, y = mpg, group = am, fill = am)) + 
  geom_bar(stat = "identity", position = position_dodge(width = 0.6))
plot_to_pptx(plt = plt, title = "Regular barchart")

# With ylimit
plt <- plt + scale_y_continuous(limits=c(10L, 50L), oob = scales::rescale_none) 
plot_to_pptx(plt = plt, title = "Ylimited regular barchart")
```

**Comment by davidgohel** [comment]
Hi

Sorry, I can see the issue in the pptx you sent but I can't reproduce your issue:

* `rescale_none` cannot be found
* if removing these unknown functions, I got the same rendering between png and vector graphics.

About the panel background, I can't see any differences between png and vector graphics, but if you want a transparent background, use `bg = "transparent"` with `addPlot`.

**Comment by itsdalmo** [comment]
Hi again,

Very sorry, I forgot to add `scales::` in front of `rescale_none`. Updated the example code in the original post. Thanks for clearing up the problem I had with transparent backgrounds also; `bg = "white"` is a new argument and default?

**Comment by davidgohel** [comment]
ok thanks, 
I can reproduce your issue

**Comment by davidgohel** [comment]
yes, `bg` is a new argument, it is used by rvg device

**Comment by davidgohel** [comment]
Sorry for that, (bug with rectangle clipping)... It should be ok now. 
Could you try with the github version please?

David

**Comment by itsdalmo** [comment]
Tested it now, and it checks out for all the examples I made - as well as some other slides. Thank you very much!.

Ps while I have your attention: `ReporteRs` states that `addMarkdown` is depreciated. What is the replacement?

**Comment by davidgohel** [comment]
cool

Yes, addMarkdown is deprecated, I will try to replace it with commonmark package later
