### ISSUE TITLE
set Dimensions to the generated ggplot vector

### ISSUE THREAD

**Issue by proadiga** [davidgohel/rvg#9]
Hello ,

```
library(officer)
library(rvg)
doc <- read_pptx("mytemplate.pptx")
doc <- add_slide(doc, "Title and Content", "Office Theme")
doc <- ph_with_vg(doc, code = print(plot), type = "body")
print(doc, target = "vg.pptx")
```

I use a based pptx file as a template and I adjust the body area in it , I make it smaller .

but the "vector-elements" will be Overlap ! 

how can I set "width" and "hieght" to the generated Vector ? 

![unbenannt](https://cloud.githubusercontent.com/assets/9284752/24036118/7a5e04a0-0af8-11e7-83c4-b1ef45852793.PNG)

**Comment by davidgohel** [comment]
add `width` and `height` in the function call (in inches).

**Comment by proadiga** [comment]
thanks David , 

so , it works . this means that I can use the other `dml_pptx` function's Parameters with `ph_with_vg` function .

**Comment by davidgohel** [comment]
I will update the doc, thanks
